# Generated by Django 4.0.4 on 2022-06-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('users_id', models.IntegerField()),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('student_number', models.CharField(max_length=45, unique=True)),
                ('nickname', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('sex', models.CharField(max_length=45)),
                ('major', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
